name: finense

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: Install dependencies
        run: |
          go version
          go get -d
      
      - name: Create env file
        run: |
          cat << EOF > .env
          ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}
          INFURA_PROJECT_ID=${{ secrets.INFURA_PROJECT_ID }}
          EOF

      - name: Run tests
        run: go test -v ./...